export const authConstant={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",

    REGISTER_REQUEST:"REGISTER_REQUEST",
    REGISTER_FAIL:"REGISTER_FAIL",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",

    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAIL:"LOGOUT_FAIL",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",

    FORGOT_PASSWORD_SUCCESS:"FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL:"FORGOT_PASSWORD_FAIL",
    FORGOT_PASSWORD_REQUEST:"FORGOT_PASSWORD_REQUEST",

    
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL:"RESET_PASSWORD_FAIL",
    RESET_PASSWORD_REQUEST:"RESET_PASSWORD_REQUEST"

}

export const affConstant={
    GET_AFFILIATE_REQUEST:"GET_AFFILIATE_REQUEST",
    GET_AFFILIATE_SUCCESS:"GET_AFFILIATE_SUCCESS",
    GET_AFFILIATE_FAIL:"GET_AFFILIATE_FAIL",

    MAKE_PROMOTER_REQUEST:"MAKE_PROMOTER_REQUEST",
    PROMOTER_REQUEST_SUCCESS:"PROMOTER_REQUEST_SUCCESS",
    PROMOTER_REQUEST_FAIL:"PROMOTER_REQUEST_FAIL",

    ACTIVATE_PROMOTER_REQUEST:"ACTIVATE_PROMOTER_REQUEST",
    ACTIVATE_PROMOTER_SUCCESS:"ACTIVATE_PROMOTER_SUCCESS",
    ACTIVATE_PROMOTER_FAIL:"ACTIVATE_PROMOTER_FAIL",
}

export const paymentConstant={
    PAYMENT_REQUEST:"PAYMENT_REQUEST",
    PAYMENT_SUCCESS:"PAYMENT_SUCCESS",
    PAYMENT_FAIL:"PAYMENT_FAIL",

    PAYMENT_VERIFY_REQUEST:"PAYMENT_VERIFY_REQUEST",
    PAYMENT_VERIFY_SUCCESS:"PAYMENT_VERIFY_SUCCESS",
    PAYMENT_VERIFY_FAIL:"PAYMENT_VERIFY_FAIL"
}

export const crossState={
    UPDATE_USER:"UPDATE_USER"
}

export const sidebarConstant={
    SIDEBAR:"SIDEBAR"
}